using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BossBullet : MonoBehaviour
{
    public float moveSpeed;
    public Rigidbody2D bulletRB;
    public int damageAmount;
    public GameObject impactEffect;

    void Start()
    {
        Vector3 direction = transform.position - PlayerHealthController.Instance.transform.position;
        float angle = Mathf.Atan2(direction.y, direction.x) * Mathf.Rad2Deg;
        transform.rotation = Quaternion.AngleAxis(angle, Vector3.forward);

        //if (AudioManager.HasInstance)
        //{
        //    AudioManager.Instance.PlaySE(AUDIO.SE_BOSS_SHOT);
        //}
    }

    void Update()
    {
        bulletRB.velocity = -transform.right * moveSpeed;
    }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Player"))
        {
            PlayerHealthController.Instance.DamagePlayer(damageAmount);
        }

        if (impactEffect != null)
        {
            Instantiate(impactEffect, transform.position, transform.rotation);
            Destroy(gameObject);
        }
    }
}
